name = "tylerbenfield-me"
compatibility_date = "2024-03-20"
pages_build_output_dir = "./dist"

# [[routes]]
# custom_domain = true
# pattern = "tylerbenfield.me"

# [[routes]]
# custom_domain = true
# pattern = "tylerbenfield.dev"